### ISSUE TITLE
Creating data_endpoint_auth keyspace fails with Cassandra 4.0

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#129]
**What happened?**
I tried created a multi-dc cluster with Cassandra 4.0. Creating the `data_endpoint_auth` keyspace fails in Cassandra with validation error. Here is the exception reported in Cassandra's log:

```
Caused by: org.apache.cassandra.exceptions.ConfigurationException: Unrecognized strategy option {dc2} passed to NetworkTopologyStrategy for keyspace data_endpoint_auth
        at org.apache.cassandra.locator.AbstractReplicationStrategy.validateExpectedOptions(AbstractReplicationStrategy.java:457)
        at org.apache.cassandra.locator.NetworkTopologyStrategy.validateExpectedOptions(NetworkTopologyStrategy.java:303)
        at org.apache.cassandra.locator.AbstractReplicationStrategy.validateReplicationStrategy(AbstractReplicationStrategy.java:402)
        at org.apache.cassandra.schema.ReplicationParams.validate(ReplicationParams.java:78)
        at org.apache.cassandra.schema.KeyspaceParams.validate(KeyspaceParams.java:94)
        at org.apache.cassandra.cql3.statements.schema.CreateKeyspaceStatement.apply(CreateKeyspaceStatement.java:87)
        at org.apache.cassandra.schema.Schema.transform(Schema.java:588)
        at org.apache.cassandra.schema.MigrationManager.lambda$announce$2(MigrationManager.java:226)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 2 common frames omitted
```

This does not happen with Cassandra 3.11.x.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
It happens just by creating a K8ssandraCluster that includes Stargate.

**Environment**

* K8ssandra Operator version:
`7a2d65bb`
* Kubernetes version information:

    `kubectl version`
    * Kubernetes cluster kind:```insert how you created your cluster: kops, bootkube, etc.    * Manifests:
    
    ```yaml
    apiVersion: k8ssandra.io/v1alpha1
    kind: K8ssandraCluster
    metadata:
      name: demo
    spec:
      cassandra:
        cluster: demo
        serverVersion: "4.0.0"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        networking:
          hostNetwork: true    
        datacenters:
          - metadata:
              name: dc1
            size: 3
            stargate:
              size: 1
              heapSize: 256M
          - metadata:
              name: dc2
            k8sContext: kind-k8ssandra-1
            size: 3
            stargate:
              size: 1
              heapSize: 256M* K8ssandra Operator Logs:```2021-09-12T17:17:56.824Z	ERROR	controller-runtime.manager.controller.k8ssandracluster	Failed to create keyspace data_endpoint_auth	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1", "error": "CALL create keyspace data_endpoint_auth failed on all datacenter dc1 pods"}github.com/k8ssandra/k8ssandra-operator/controllers.(*K8ssandraClusterReconciler).reconcile
	/workspace/controllers/k8ssandracluster_controller.go:224
github.com/k8ssandra/k8ssandra-operator/controllers.(*K8ssandraClusterReconciler).Reconcile
	/workspace/controllers/k8ssandracluster_controller.go:79
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```

**Anything else we need to know?**:
I had 4 worker nodes per kind cluster.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-889) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆Affected Versions: k8ssandra-operator-1.0.0-alpha.1
┆Fix Versions: k8ssandra-operator-1.0.0-alpha.1
┆Issue Number: K8SSAND-889
┆Priority: Medium

**Comment by adejanovski** [comment]
This was fixed by #145 

Cassandra 4.0 doesn't allow putting replicas on non-existent datacenters (which previous versions allowed).
The workaround here has been to create the CassandraDatacenter objects first and only then create the Stargate deployments. The keyspace is then created when the datacenters all exist in the cluster.
We've also covered expansions to new datacenters by running `ALTER KEYSPACE` statements, which uncovered a bug related to Stargate: https://github.com/stargate/stargate/issues/1274
As a workaround, #145 also enables a Cassandra flag which allows changing the replication factor during range movements, which got prohibited by default in 4.0. The flag is enabled only if the Cassandra version is >= 4.0 and Stargate pods are deployed.
