### ISSUE TITLE
When trying to install a mulit-cluster demo Stargate won't start up

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#138]
**What did you do?**

Went through the multi-cluster kind based install guide and during the deployment Stargate would not start, in the logs for the pod it showed an error:

```
Sep 14, 2021 3:50:55 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method get in io.stargate.web.swagger.SwaggerUIResource contains empty path annotation.

INFO  [main] 2021-09-14 15:50:55,511 ContextHandler.java:916 - Started i.d.j.MutableServletContextHandler@5e057ef{/,null,AVAILABLE}
INFO  [main] 2021-09-14 15:50:55,519 AbstractConnector.java:331 - Started Server@6e741ba6{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
INFO  [main] 2021-09-14 15:50:55,520 Server.java:415 - Started @38994ms
INFO  [main] 2021-09-14 15:50:55,520 BaseActivator.java:185 - Started restapi
Finished starting bundles.
Unexpected error: java.io.IOException: User limit of inotify instances reached or too many open files
java.lang.RuntimeException: java.io.IOException: User limit of inotify instances reached or too many open files
    at io.stargate.starter.Starter.watchJarDirectory(Starter.java:539)
    at io.stargate.starter.Starter.start(Starter.java:441)
    at io.stargate.starter.Starter.cli(Starter.java:619)
    at io.stargate.starter.Starter.main(Starter.java:660)
Caused by: java.io.IOException: User limit of inotify instances reached or too many open files
    at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
    at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
    at io.stargate.starter.Starter.watchJarDirectory(Starter.java:526)
    ... 3 more
INFO  [StorageServiceShutdownHook] 2021-09-14 15:50:55,583 HintsService.java:209 - Paused hints dispatch
```

**Did you expect to see some different?**

I expected things to install and run normally since it's just a demo deployment.

**Environment**

* K8ssandra Operator version:

`k8ssandra/k8ssandra-operator:7a2d65bb`

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-07-12T20:40:20Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Kind on Ubuntu

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-900) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-900
┆Priority: Medium

**Comment by jdonenine** [comment]
I created this issue so that I could document the answer to my own question once I figured it out.

On my system (`Ubuntu 20.04.2 LTS`) the solution was to increase the `inotify` limits on the system.

This can be done with a command like:

`sudo sysctl fs.inotify.max_user_instances=256`

and/or by adding a permanent entry to `/etc/sysctl.conf`
