### ISSUE TITLE
Vector error when parsing Cassandra logs

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/k8ssandra-operator#1409]
A user is observing the following error:
```
thread 'vector-worker' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/onig-6.4.0/src/lib.rs:648:23:
Onig: Regex search error: retry-limit-in-match over
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'vector-worker' panicked at src/topology/builder.rs:920:30:
internal error: entered unreachable code: join error or bad poll
2024-09-13T16:31:52.484789Z ERROR transform{component_kind="transform" component_id=parse_cassandra_log component_type=remap}: vector::topology: An error occurred that Vector couldn't handle: the task panicked and was aborted.
2024-09-13T16:31:52.484869Z  INFO vector: Vector has stopped.
```
Which points to the [regex](https://github.com/k8ssandra/k8ssandra-operator/blob/3d3d735bc72056afee9a54d96f5c4d05159cd6a4/pkg/telemetry/vector.go#L144) that we use to parse Cassandra system logs. It looks like we ran into an unexpected log format that the regex fails on.

Unfortunately this causes a panic and a restart of the container, see vectordotdev/vector#15199.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-255) by [Unito](https://www.unito.io)

**Comment by olim7t** [comment]
Possibly relevant: the server version is DSE 6.9.
