### ISSUE TITLE
K8SSAND-1428 ⁃ Stargate config generation does not work correctly for 4.0

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra-operator#189]
**What happened?**
When implementing #130 it became clear that the tests themselves are not working. So implementing running tests against multiple versions will not pass since the tests are broken.

This is because while we do remove 4.0 properties from Cassandra deployment, it's not done correctly for Stargate which has all those 3.11 properties for Stargate 4.0 deployment and that fails.

```
 Caused by: org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [start_rpc, thrift_prepared_statements_cache_size_mb] from your cassandra.yaml
	at org.apache.cassandra.config.YamlConfigurationLoader$PropertiesChecker.check(YamlConfigurationLoader.java:275)
	at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:130)
	at io.stargate.db.cassandra.Cassandra40PersistenceActivator.makeConfig(Cassandra40PersistenceActivator.java:66)
```

**Did you expect to see something different?**
I expected them to work since this type of removal of unused parameters is what cass-config-builder should do.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1428) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1428
┆priority: Medium

**Comment by bradfordcp** [comment]
Is this ticket obsolete @burmanm

**Comment by jsanda** [comment]
The offending properties were removed in bd8af171793933bea3f11c848d090433fb0642c2. 

@burmanm please reopen if there is more to be done here.
