### ISSUE TITLE
K8SSAND-1204 ⁃ Flaky e2e tests

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#343]
**What happened?**
We have some flaky e2e tests that are producing intermittent failures across various PRs. I was investigating recent failures from a couple different tests and noticed that management-api was logging errors due to too many open files:

```
ERROR [nioEventLoopGroup-3-1] 2022-02-01 10:46:16,930 NodeOpsResources.java:525 - Error when executing request
java.lang.IllegalStateException: failed to create a child event loop
...
Caused by: io.netty.channel.ChannelException: failed to open a new selector
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        ... 57 common frames omitted
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.IOUtil.makePipe(Native Method)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
```

I am seeing this in tests that deploy 2 DCs with 3 nodes per DC. It happens on the last Cassandra pod. 

**Did you expect to see something different?**
We shouldn't be hitting resource limits. It's not possible to increase resource limits like open files in the GHA runners, but hopefully we make other changes to avoid this. 

The management-api is deployed with its default heap size of 128 MB. In the past we deployed it with as little as 16 MB for tests. I can't say for certain that lowering the heap will help, but it's worth a shot.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1204) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1204
┆priority: Medium

**Comment by jsanda** [comment]
`MultiDcAuthOnOff` is one of the flaky tests. In a recent failure it timed out waiting for Reaper to become ready in DC1. There were no errors in the updated Reaper pod logs. Looking at timestamps, I could see it was running for 5+ minutes and hadn't yet fully initialized. The timeout for the Reaper readiness check is set to 5 minutes. We might simply need to increase this timeout for GHA.
