### ISSUE TITLE
k8ssandra-operator pod CrashLoopBackoff panic: runtime error in replicatedsecret controller

### ISSUE THREAD

**Issue by rocket357** [k8ssandra/k8ssandra-operator#892]
```
2023-02-21T16:04:03.977Z        INFO    Starting reconciliation {"controller": "replicatedsecret", "controllerGroup": "replication.k8ssandra.io", "controllerKind": "ReplicatedSecret", "ReplicatedSecret": {"name":"sre-test-cassandra","namespace":"development"}, "namespace": "development", "name": "sre-test-cassandra", "reconcileID": "3951cd68-fcf7-4b70-baaa-36b4a7e0b53c", "key": {"namespace": "development", "name": "sre-test-cassandra"}}
2023-02-21T14:53:10.751Z        INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "K8ssandraCluster": {"name":"sre-test-cassandra","namespace":"development"}, "namespace": "development", "name": "sre-test-cassandra", "reconcileID": "96d449f7-1011-4ed2-800a-c016e5037e40"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15462bf]

goroutine 890 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x16fc2a0, 0x27826c0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).createDatacenterConfigs(0xc0002b5450, {0x1ba0718, 0xc0015261e0}, 0xc001054d00, {{0x1ba2f68?, 0xc001526240?}, 0xb?}, 0x12?)
        /workspace/controllers/k8ssandra/dcconfigs.go:66 +0x91f
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcileDatacenters(0xc0002b5450, {0x1ba0718, 0xc0015261e0}, 0xc001054d00, {{0x1ba2f68?, 0xc001526240?}, 0x0?})
        /workspace/controllers/k8ssandra/datacenters.go:43 +0x18e
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcile(0xc001054d00?, {0x1ba0718, 0xc0015261e0}, 0xc001054d00, {{0x1ba2f68?, 0xc001526240?}, 0xc000b7bd80?})
        /workspace/controllers/k8ssandra/k8ssandracluster_controller.go:143 +0x2e5
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).Reconcile(0xc0002b5450, {0x1ba0718, 0xc0015261e0}, {{{0xc000b7bd80, 0xb}, {0xc0003bbf20, 0x12}}})
        /workspace/controllers/k8ssandra/k8ssandracluster_controller.go:91 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ba0670?, {0x1ba0718?, 0xc0015261e0?}, {{{0xc000b7bd80?, 0x1835d40?}, {0xc0003bbf20?, 0x4045d4?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005c0f00, {0x1ba0670, 0xc0002d6dc0}, {0x175d980?, 0xc0004de8e0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005c0f00, {0x1ba0670, 0xc0002d6dc0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
```

**How to reproduce it (as minimally and precisely as possible)**:
Deployed via "wrapper" helm chart (platops-k8ssandra-operator), deploying k8ssandra-operator helm chart 0.39.3 (app ver 1.5.0).  Installs and upgrades without issue.  Above issue arises when deploying a minimal k8ssandracluster.yaml:

```apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: sre-test-cassandra
  namespace: development
spec:
  reaper:
    autoScheduling:
      enabled: true
  cassandra:
    datacenters:
    - metadata:
        name: us-central1
        namespace: development
      size: 3
      config:
        cassandraYaml:
          num_tokens: 256
          authenticator: org.apache.cassandra.auth.PasswordAuthenticator
          authorizer: org.apache.cassandra.auth.CassandraAuthorizer
          role_manager: org.apache.cassandra.auth.CassandraRoleManager
      racks:
      - name: "us-central1-a"
        nodeAffinityLabels:
          failure-domain.beta.kubernetes.io/zone: us-central1-a
      - name: "us-central1-b"
        nodeAffinityLabels:
          failure-domain.beta.kubernetes.io/zone: us-central1-b
      - name: "us-central1-f"
        nodeAffinityLabels:
          failure-domain.beta.kubernetes.io/zone: us-central1-f
      serverImage: us.gcr.io/alv-dev-shared-artifacts-ad4a/platops/cassandra:3.11.9
      storageConfig:
        cassandraDataVolumeClaimSpec:
          storageClassName: "ssd-zonal"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G
```

**Environment**
GKE

* K8ssandra Operator version:

    `v1.5.0`

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9-gke.2000", GitCommit:"d88d51328da8c0d8b81437d425907bb5a9260a44", GitTreeState:"clean", BuildDate:"2023-01-04T09:38:24Z", GoVersion:"go1.18.9b7", Compiler:"gc", Platform:"linux/amd64"}
`

* Kubernetes cluster kind:

    Terraform/GKE

Let me know if there is any additional information I can provide.

**Comment by adejanovski** [comment]
I've seen that happening a few times now during upgrades, but can't remember what's really causing this.
The easy workaround is to add a `.spec.cassandra.serverType`  entry with a value of `cassandra`.
It's the field that's missing here.

**Comment by rocket357** [comment]
Ha! As soon as I typed up that response, the next field seems to have "fixed" the issue: `serverVersion`.

**Comment by adejanovski** [comment]
Right, this one as well 😅

**Comment by rocket357** [comment]
Ok, this issue can be closed.  Adding `serverType` and `serverVersion` fixed the crash.
